### ISSUE TITLE
Presidential Fellows Logo link doesn't work for some pages

### ISSUE THREAD

**Issue by davidewarren** [presidential-innovation-fellows/pif-website#156]
- The Presidential Fellow Logo in the upper right hand corner of every page does not direct the user to the home page. 

- This should be changed to direct users to https://presidentialinnovationfellows.gov/

**Comment by ver-kat** [comment]
I'm assuming you mean the one in the upper left? If so, I can reproduce. It links back to the same page. I'll see if I can debug.

**Comment by ver-kat** [comment]
This can be fixed by adding a "/" in this line in header.html:
        <a class="navbar-brand" href="{{ site.baseurl }}">
becomes:
        <a class="navbar-brand" href="{{ site.baseurl }}/">

Basically, this forces a value of "/" to be set to the href. However, "{{ site.baseurl }}" does not seem to evaluate to anything in the browser, and I don't know enough about the code to understand why, so I'm not comfortable making this fix right now. I'll see if I can understand the code a bit more if I get a chance, but if someone else wants to take a stab at it, go ahead.

**Comment by davidewarren** [comment]
Closing this issue - This was fixed at some point in the past year under a different update
