### ISSUE TITLE
“Apply Today” button in header should link to "application closed”

### ISSUE THREAD

**Issue by davidewarren** [presidential-innovation-fellows/pif-website#159]
- Currently the "Apply Today" button in the header directs the user to an application submission page - https://apply.pif.gov/ 

- It should direct the user to the following application closed page - https://presidentialinnovationfellows.gov/application-closed/

**Comment by ver-kat** [comment]
I do not see the "application closed" button. Has it been removed? If not, which page is it on?

**Comment by ver-kat** [comment]
I'm seeing the "Apply Today" button on my tablet, but not on my computer. Maybe a separate defect. I will also try to debug that issue.

**Comment by ver-kat** [comment]
I found where to fix the link, but the "application closed" page says it will reopen in February, so I'm wondering if it should be fixed if it will need to be changed back in a couple of weeks? 
Also, I found the code that hides the button in certain cases, and it seems to be by design, so I'm going to assume that is not something that needs to be fixed.

**Comment by ver-kat** [comment]
One more idea, if the application window is during certain months, logic could be added to have the link be the application submission page during those months, and the application closed page during the other months.

**Comment by davidewarren** [comment]
closing this issue - button now correctly redirect to the application closed page
