### ISSUE TITLE
Redirects don't work over HTTPS

### ISSUE THREAD

**Issue by gbinal** [presidential-innovation-fellows/pif-website#52]
https://www.presidentialinnovationfellows.gov doesn't resolve for me in Chrome.  Interestingly, www.presidentialinnovationfellows.gov does, but https://www.presidentialinnovationfellows.gov doesn't.

**Comment by rossdakin** [comment]
The basic issue is that the S3 buckets that currently handle domain redirects don't support HTTPS.

I set up a proof of concept that proxies through a new CloudFront distribution to allow HTTPS to the redirect domain names (try it: https://test.pif.gov) but then we have the issue of no valid SSL certs for those domain names.

Looks like this:
![pif website infra](https://cloud.githubusercontent.com/assets/44956/9318217/a9e5e0f4-450f-11e5-9ea6-1a2274a55f43.png)

So, we could get SSL certs for any redirect domains (pif.gov, etc.) and install them in the redirect CloudFront distro. That would work. The only catch is that it would be expensive ($600/mo.) if we cared about supporting old non-SNI browsers – I would argue that it's such a corner case (old browser + manually enters the domain name with https) that we don't need the dedicated IP (can just use HTTPS via SNI).

If we want to fix this:
 1. order SSL certs for each redirect domain name (or ideally a UCC cert "all in one")
 2. install it on the new CloudFront distro (E3TEF3880Q2YXR)
 3. :us:

**Comment by stroupaloop** [comment]
If I understand the issue correctly, would having a wildcard SSL cert for pif.gov and presidentialinnovationfellows.gov solve this problem? If so, we can get those so we don't have to deal with these in the future plus support various subdomains for PIF projects.

**Comment by rossdakin** [comment]
Yep!

The other decision to make is whether or not to support these redirects
over HTTPS on non-SNI browsers (i.e. HTTPS for the alias domains in IE 6 or
any Win XP). That's another $600'ish per month for the dedicated IPs per
cert, which feels like a steep price to pay for a corner case, but that's
my startup frugality talking – perhaps rules exist about mandated support
for older browsers, I don't know.

Either way, wildcard certs would be the starting point.


On Wednesday, August 19, 2015, Andrew Stroup <notifications@github.com>
wrote:

> If I understand the issue correctly, would having a wildcard SSL cert for
> pif.gov and presidentialinnovationfellows.gov solve this problem? If so,
> we can get those so we don't have to deal with these in the future plus
> support various subdomains for PIF projects.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/pif-website/issues/52#issuecomment-132828774>.
>


-- 
Ross Dakin
Presidential Innovation Fellow
(202) 286-0143
ross.dakin@pif.gov
https://www.whitehouse.gov/innovationfellows

**Comment by gbinal** [comment]
@konklone has done a lot of research on this but tl;dr, it's really worth looking at your analytics and be really open to not supporting XP anymore.  For this website in particular, I'm not sure it needs to support legacy setups like this.

**Comment by konklone** [comment]
In consultation with the DAP, we started requiring SNI for analytics.usa.gov and stopped paying the $600/month.

The affected audience is **IE on Windows XP** -- Firefox and Chrome on Windows XP should handle SNI correctly. This was a very small % of traffic for analytics.usa.gov, and well worth the cost savings.

There are some other affected non-browser clients, like Python 2.7.8 and below, but since the site isn't hosting an API and likely isn't in the near future, it should be safe.

**Comment by rossdakin** [comment]
:+1: 

I'm all for doing our part to move the web forward.

**Comment by stroupaloop** [comment]
I worked with @konklone on this issue and we're in the process of purchasing the wildcart cert for pif.gov. The credits on SSLMate are out so I'm waiting for that update based on a purchase form submission.

Reading through this again, I don't think we need a wildcart cert for presidentialinnovationfellows.gov, but let me know if I'm wrong. Trying to save money but the only thing that will every be attached to presidentialinnovationfellows.org is the actual website whereas pif.gov will host alpha / beat products and other services we self host. Thanks!

**Comment by konklone** [comment]
@stroupaloop Yeah, you don't need a wildcard cert for presidentialinnovationfellows.gov. The single-domain cert you have is already valid for both the root and www -- but you have www pointed at an S3 bucket, which has no mechanism for using the cert.

**Comment by stroupaloop** [comment]
So I was able to purchase the *.pif.gov wildcard cert and added into AWS CloudFront.

I've then assigned cert for the redirect CF distro to the wildcard cert as seen below, but when entering pif.gov the redirect is still over HTTP instead of HTTPS. Am I missing a step about forcing HTTPS for the distro?

![image](https://cloud.githubusercontent.com/assets/2424551/10978466/1a405d86-83c5-11e5-8d8e-d9172f630e39.png)

**Comment by stroupaloop** [comment]
additionally, https://www.presidentialinnovationfellows.gov does not redirect to https://presidentialinnovationfellows.gov. I'm guessing this is the same issue as the pif.gov redirect over HTTPS, but does this also mean a wildcard cert would also be required to resolve this?

**Comment by konklone** [comment]
@stroupaloop I think the redirect setting is in a different part of the distribution settings -- I can't review in detail now but can work with you later on to figure that out.

You don't need a wildcard cert for presidentialinnovationfellows.gov, as the cert you have for the root is also good for `www`. The redirect issue from www->root over HTTPS, I'll also need to take a look at. Find me on Slack or something during the day when we're free and we can poke through the settings.

**Comment by stroupaloop** [comment]
Ok ... so the following use cases are still un resolved following the below method (root.gov = presidentialinnovationfellows.gov):

3 CoudFront (SNI only) distributions
- presidentialinnovationfellows.gov and www.presidentialinnovationfellows.gov
- pif.gov
- www.pif.gov

4 S3 buckets
- presidentialinnovationfellows.gov (root director for website)
- www.presidentialinnovationfellows.gov (redirect to https://presidentialinnovationfellows.gov)
- pif.gov (redirect to https://presidentialinnovationfellows.gov)
- www.pif.gov (redirect to https://presidentialinnovationfellows.gov)

Route 53 settings
- presidentialinnovationfellows.gov > CloudFront distro
- www.presidentialinnovationfellows.gov > S3 bucket
- pif.gov > S3 bucket
- www.pif.gov > S3 bucket

This configuration still does not address any https:// redirects for
- www.presidentialinnovationfellows.gov
- pif.gov
- www.pif.gov

**Comment by konklone** [comment]
> I suppose the bigger question is that at this point would it make more sense to spin up micro EC2 instancesn that handle the redirects over nginx?

Hmm, maybe @dhcole would have the right idea here, since he's handled this for `sbst.gov`.

It looks like he pointed both `sbst.gov` and `www.sbst.gov` DNS at the same CloudFront distribution, and so if you visit `https://www.sbst.gov` it gives you a 200:

```
$ curl --head https://www.sbst.gov
HTTP/1.1 200 OK
```

But it performs the redirect in JavaScript, as seen in the source code:

```html
  <script>
    if (/^www\./.test(window.location.hostname)) {
      window.location = window.location.href.replace('www.', '');
    }
  </script>
```

You could do something similar with `pif.gov` and `www.pif.gov`, where you point them to a second CloudFront distribution that points to the **master** `presidentialinnovationfellows.gov` S3 bucket (not to a redirect bucket) and then redirect in JS if the domain is wrong.

Or, you could set up a proxy EC2 server, as annoying as that is (though it's what [NASA did too](https://twitter.com/konklone/status/644624698706411520)). Maybe Federalist has something already set up for that? If not, it's probably a helpful general service for us to set up. And the uptime stakes are pretty low for non-canonical hostname redirects anyway.

**Comment by dhcole** [comment]
I would do the following:

- S3 bucket: `pif-redirect` that uses the global redirect setting to send all requests to https://presidentialinnovationfellows.gov
- CF distro for redirects that uses the `pif-redirect` bucket as its origin and has the following configuration
  - CNAMEs for each redirect domain, including www.presidentialinnovationfellows.gov
  - SSL certs for each domain
  - "Redirect HTTP to HTTPS" setting on the behavior
  - "Always use HTTP" on the origin config (can't do it any other way with S3, sadly)
- Route53 ALIAS records for each redirect domain to the above CF distro
- An additional primary distro for the `presidentialinnovationfellows.gov` domain:
  - uses the `presidentialinnovationfellows.gov` bucket as its origin
  - has the ssl cert for `presidentialinnovationfellows.gov`
  - "Redirect HTTP to HTTPS" setting on the behavior
  - "Always use HTTP" on the origin config
- Route53 ALIAS record for `presidentialinnovationfellows.gov` to the above primary domain

Assuming I haven't missed a case, this should get you redirecting all of the domains to a single origin (https://presidentialinnovationfellows.gov) over http and https with just two CF distros and two S3 buckets

Let me know if you want to talk through this over voice. 

The JS redirect works too, but it's not super ideal. I use it for Federalist sites to avoid because we'd need an S3 bucket for each site to make the redirect work, which would be a lot of waste. For one site like this, you could have a single redirect bucket handle multiple domains.

**Comment by dhcole** [comment]
> I suppose the bigger question is that at this point would it make more sense to spin up micro EC2 instancesn that handle the redirects over nginx

The problem with this is it's a single point of failure. If the instance dies for any reason (sometimes they just fail in AWS), your redirects would go down. Also, you'd want to keep up with security patches on the instance.

**Comment by konklone** [comment]
@dhcole I _think_ that @stroupaloop set up something like you described and it wasn't working for mysterious reasons. The `pif.gov` and `www.pif.gov` domains were rendering a 403 S3 error for no bucket access, even though they appeared to be properly configured as redirect buckets. But we might have made a misconfiguration in there somewhere that we weren't spotting.

**Comment by s2t2** [comment]
Given the links in question (pif.gov, www.pif.gov, http://pif.gov, http://www.pif.gov, http://www.presidentialinnovationfellows.gov, http://presidentialinnovationfellows.gov, www.presidentialinnovationfellows.gov) all now resolve to HTTPS, I recommend we close this issue.
