### ISSUE TITLE
HSTS preloaded

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/pif-website#57]
https://18f.gsa.gov/2015/02/09/the-first-gov-domains-hardcoded-into-your-browser-as-all-https/

**Comment by rossdakin** [comment]
Looks like the requisite `Strict-Transport-Security` header [may not be an option](https://forums.aws.amazon.com/thread.jspa?messageID=580720) on S3 sites.

@konklone, any insight into HSTS via S3/CloudFront?

Also, what's the state of HSTS for GitHub pages, out of curiosity?

**Comment by konklone** [comment]
> @konklone, any insight into HSTS via S3/CloudFront?

Ugh, right, I'd forgotten about this. We use S3/CloudFront for analytics.usa.gov, but I hadn't used it for a second-level domain yet.

> Also, what's the state of HSTS for GitHub pages, out of curiosity?

Nothin'.

So, I'd really like to fix this. We should be able to host things cheaply, but also, it's really important to get HSTS in place for second-level .gov domains. For subdomains like analytics.usa.gov, they can [piggy back off of the HSTS policy](https://https.cio.gov/guide/) of their parent domain, but second-level domains really need to set it themselves.

One way that comes to mind is to replace the S3 portion with 18F's CloudFoundry setup, which would also let you set up auto-deployment with webhooks. So, pushing to some branch here would auto-deploy to `pif-site.18f.gov`, and then you would configure your CloudFront distribution to proxy to that domain. 18F's CloudFoundry automatically forces HTTPS and sets HSTS headers, but doesn't include `includeSubDomains` -- but you could modify the underlying staticfile buildpack to set that header yourself, and 18F's CloudFoundry will pass on the stronger header instead of overwriting it.

Another route is to replace the CloudFront portion with another service like Cloudflare that sets that header for you, but I'm not sure of the approval process for that for the PIF program.

Another route would be to use [18F Pages](https://18f.gsa.gov/2015/05/14/18Fpages/) as the deployed site. I'm not sure what the HSTS story is there, but I bet @mbland would help you figure it out. The main issue there is you'd be proxying from your custom domain to a domain with a path prefix -- `https://pages.18f.gov/pif-site/` -- but that may not be a big deal, I think you could leave the absolute asset path URLs and just let the site look broken on the pages.18f.gov version -- it would work fine in the proxied version.

Another route is to beseech Amazon to fix this oversight, but either way is a nontrivial change: S3 can't allow people to accidentally set HSTS policy for their entire `s3.amazonaws.com` domain, or potentially subdomains that could be other people's bucket names. CloudFront doesn't currently inject any custom headers at all, so adding it would be a change. I have in fact reported this to Amazon and I know they're aware of the issue -- I don't expect anything to be fixed in the immediate future.

**Comment by s2t2** [comment]
Given S3 is no longer being used to serve assets, I recommend we close this issue.
