### ISSUE TITLE
Unable to upload the _site folder to S3 using s3_website gem

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/pif-website#83]

**Comment by rossdakin** [comment]
Can't release?

Get an error?

**Comment by stroupaloop** [comment]
@rossdakin the actual s3_website.yml isn't on this repo as it contains AWS credentials, but the output that I'm receiving when executing the push command is the following ...

![image](https://cloud.githubusercontent.com/assets/2424551/10768846/6e2a7584-7cb9-11e5-944e-633d9269c407.png)

**Comment by rossdakin** [comment]
It took about 5 minutes, but worked for me:

<img width="1011" alt="screen shot 2015-10-27 at 5 00 02 pm" src="https://cloud.githubusercontent.com/assets/44956/10772369/2f133256-7ccc-11e5-9588-0ea8491aaff4.png">

Looks like your process may have run out of memory — I wonder if there's some inefficiency in the s3_website gem that chokes the JVM.

Smells like it may be the "runaway recursion in file listing" fixed by [2.11.1](https://github.com/laurilehmijoki/s3_website/blob/master/changelog.md#2111). Maybe do a `bundle update` and try again (committing the new Gemfile.lock if it works).

**Comment by stroupaloop** [comment]
Hm weird, I tried again with the updated gem and it still bombs out in java land with an out of memory error. I also removed the entire repo and re-cloned it, but same results.

**Comment by rossdakin** [comment]
Looks like you're not the only one: https://github.com/laurilehmijoki/s3_website/issues/181

There are some suggestions in that issue that might help.

**Comment by stroupaloop** [comment]
apparently this is a personal problem for me but a known issue by the s3_website creators. Waiting for an official fix.
